version: "3"

services:
  mysql:
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./files/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
